### ISSUE TITLE
Документация рекомендует делать иначе 

### ISSUE THREAD

**Issue by rodion-goritskov** [hwn123/csitest2#1]
https://github.com/hwn123/csitest2/blob/2f64e8f0f0b2de5ffa12f699ccf7054a7c96ab41/ansible/roles/docker/tasks/main.yml#L17

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - foo
    - foo-tools

**Comment by hwn123** [comment]
Какая документация, и чем это лучше?

**Comment by hwn123** [comment]
Корректнее было бы привести не пример, а его объяснение:
> When used with a loop: each package will be processed individually, it is much more efficient to pass the list directly to the name option.
Это комментарий появился в ansible с версии 2.5, возможно, ранее list не мог быть использован как параметр, т.к. применение with_items весьма распространено и является универсальным решением.
Так или иначе, переход на использование list оправдано.
